# serverless/serverless.yml

service: orders-service

frameworkVersion: "3"

provider:
  name: aws
  region: us-east-1

functions:
  deleteData:
    package:
      artifact: ./bin/deleteData.zip
    handler: bootstrap
    runtime: provided.al2

    events:
      - http:
          path: deleteData
          method: delete

  getData:
    package:
      artifact: ./bin/getData.zip
    handler: bootstrap
    runtime: provided.al2

    events:
      - http:
          path: get-data
          method: post

custom:
  scriptable:
    hooks:
      before:package:createDeploymentArtifacts: make build

package:
  individually: true

plugins:
  - serverless-scriptable-plugin
