# serverless/serverless.yml

service: orders-service

frameworkVersion: "3"

provider:
  name: aws
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchWriteItem
            - dynamodb:BatchGetItem
          Resource:
            - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/*"
            - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/*/index/*"
        - Effect: Allow
          Action:
            - s3:*
          Resource:
            - "*"
        - Effect: Allow
          Action:
            - scheduler:CreateSchedule
            - scheduler:DeleteSchedule
          Resource:
            - "*"
        - Effect: Allow
          Action:
            - iam:PassRole
          Resource:
            - !Sub
              - arn:aws:iam::${AWS::AccountId}:role/ScheduledEventExecutionRole
              - {}
        - Effect: Allow
          Action:
            - sqs:SendMessage
          Resource:
            - !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:*"
        - Effect: Allow
          Action:
            - events:PutEvents
          Resource:
            - !Sub "arn:aws:events:${AWS::Region}:${AWS::AccountId}:event-bus/*"

functions:
  deleteOrder:
    package:
      artifact: ./bin/deleteOrder.zip
    handler: bootstrap
    runtime: provided.al2

    events:
      - http:
          path: deleteOrder
          method: delete

  getData:
    package:
      artifact: ./bin/getData.zip
    handler: bootstrap
    runtime: provided.al2

    events:
      - http:
          path: get-data
          method: post

  addData:
    package:
      artifact: ./bin/addData.zip
    handler: bootstrap
    runtime: provided.al2

    events:
      - http:
          path: add-order
          method: post
custom:
  scriptable:
    hooks:
      before:package:createDeploymentArtifacts:
        - make build

package:
  individually: true

plugins:
  - serverless-scriptable-plugin
  - serverless-iam-roles-per-function
  - serverless-dotenv-plugin
